version: 0.2

phases:
  install:
    commands:
      ## 依存パッケージをインストール
      - npm install
  build:
    commands:
      ## テスト実行
      - npm test
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - "**/*"