site_name: CI/CDハンズオン
nav:
  - トップ: README.md
  - CI/CDとは: what-is-ci-cd.md
  - 使用するサービスの説明: code-series.md
  - 全体構成: architecture.md
  - パイプライン構築の準備: preparation.md
  - CodeDeploy: codedeploy.md
  - CodePipeline: codepipeline.md
  - 自動デプロイ！: auto_deploy.md
  - テスト失敗時にデプロイが止まることを確認: stop-when-test-failed.md
  - 参考情報: reference.md
  - まとめ: conclusion.md
theme: material